// Turn a directory of .txt files into a corpus profile.
//
//   node scripts/build-profile.mjs <corpus-dir> <de|en>
//
// Run it once per language with the reference corpus, then commit the generated
// src/profiles.ts. Run it against your own texts to measure against your own
// register instead: a profile built from ten of your own reports says something
// far more useful about an eleventh than a profile built from dissertations.
//
// The corpus texts themselves are never copied into this repo. Only the
// distribution is, which is nineteen numbers per feature and no recoverable
// prose. See src/profile.ts for why that is the unit.

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { buildProfile } from "../dist/profile.js";

const [dir, lang] = process.argv.slice(2);

if (!dir || (lang !== "de" && lang !== "en")) {
  console.error("usage: node scripts/build-profile.mjs <corpus-dir> <de|en>");
  process.exit(2);
}

const files = readdirSync(dir)
  .filter((f) => f.endsWith(".txt"))
  .sort();

if (files.length < 2) {
  console.error(`need at least 2 .txt files in ${dir}, found ${files.length}`);
  process.exit(2);
}

const texts = files.map((f) => readFileSync(join(dir, f), "utf8"));
const profile = buildProfile(texts, lang);

console.log(`${lang}: ${profile.sources} texts, ${profile.words.toLocaleString("en")} words`);

const outPath = join("profiles", `${lang}.json`);
writeFileSync(outPath, JSON.stringify(profile, null, 2) + "\n");
console.log(`wrote ${outPath}`);

embedProfiles();

/**
 * Regenerate src/profiles.ts from whatever profiles/*.json exist.
 *
 * The profiles are embedded as a TypeScript module rather than imported as JSON
 * so that the browser demo can load the library as plain ES modules with no
 * bundler and no fetch. A JSON import would need an import attribute in Node and
 * a separate network request in the browser, and the demo exists partly to prove
 * the published ESM output runs unmodified in a browser.
 */
function embedProfiles() {
  const langs = ["de", "en"].filter((l) => {
    try {
      readFileSync(join("profiles", `${l}.json`), "utf8");
      return true;
    } catch {
      return false;
    }
  });

  const entries = langs
    .map((l) => {
      const json = JSON.parse(readFileSync(join("profiles", `${l}.json`), "utf8"));
      return `  ${l}: ${JSON.stringify(json, null, 2).replace(/\n/g, "\n  ")},`;
    })
    .join("\n");

  const header = `// Generated by scripts/build-profile.mjs. Do not edit by hand.
//
// The measured distributions, one per language. These are statistics over a
// reference corpus, not the corpus itself: see src/profile.ts for why that
// distinction is the design rather than a detail.

import type { CorpusProfile } from "./profile.js";
import type { Lang } from "./tokenize.js";

export const PROFILES: Readonly<Record<Lang, CorpusProfile>> = {
${entries}
} as unknown as Readonly<Record<Lang, CorpusProfile>>;

/** The bundled profile for a language. */
export function profileFor(lang: Lang): CorpusProfile {
  return PROFILES[lang];
}
`;

  writeFileSync(join("src", "profiles.ts"), header);
  console.log(`wrote src/profiles.ts (${langs.join(", ")})`);
}
